name: CycascMainCommands
version: '1.8.6-paper1.21.1'
main: net.cycasc.mc.cycascMainCommands.CycascMainCommands
api-version: '1.21'
authors: [ Dunkelklinge1 ]
description: Minecraft server plugin which provides a few more basic commands (nothing earth-shattering).
website: https://www.cycasc.net
commands:
  listonline:
    description: Lists all online players.
    usage: "Usage: /listonline"
  kill:
    description: Kills a player.
    usage: "Usage: /kill [player]"
  tp:
    description: Teleports players.
    usage: "Usage: /tp [player 1] <player 2> OR /tp [player] [world] <x> <y <z>"
  serverinfo:
    description: Lists general information about the server.
    usage: "Usage: /serverinfo"
  playerinfo:
    description: Lists general information about the specified player.
    usage: "Usage: /playerinfo <player>"
