name: CycascMainCommands
version: 1.8.6-spigot1.20.1
author: Dunkelklinge1
website: https://www.cycasc.net

main: net.cycasc.mc.cycascmaincommands_main.MainCycascMainCommands

commands:
  listonline:
    description: Lists all online players.
    usage: "Usage: /listonline"
  kill:
    description: Kills a player.
    usage: "Usage: /kill [player]"
  tp:
    description: Teleports players.
    usage: "Usage: /tp [player 1] <player 2> OR /tp [player] [world] <x> <y <z>"
  serverinfo:
    description: Lists general information about the server.
    usage: "Usage: /serverinfo"
  playerinfo:
    description: Lists general information about the specified player.
    usage: "Usage: /playerinfo <player>"